package com.mido.studenttaskmanager.data

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * [Task] represents a single task item in the application.
 * It is also defined as a Room [Entity], meaning it corresponds to a table in the database.
 *
 * @property id The unique identifier for the task. It is auto-generated by the database.
 *              Defaults to 0 when creating a new task, as Room will assign a unique ID.
 * @property title The title of the task. This field is mandatory.
 * @property description A detailed description of the task. This field is optional.
 * @property isCompleted A boolean flag indicating whether the task has been completed.
 *                       Defaults to `false` for new tasks.
 */
@Entity(tableName = "tasks_table") // Designates this data class as a Room entity, mapping it to a database table named "tasks_table".
data class Task(
    @PrimaryKey(autoGenerate = true) // Specifies that 'id' is the primary key and its value will be automatically generated by the database.
    val id: Int = 0, // Provides a default value for 'id'. Room will ignore this when autoGenerate is true for new entries.
    val title: String,
    val description: String,
    var isCompleted: Boolean = false // A mutable property to allow toggling completion status.
)